config/routes.rb
Basecramp::Application.routes.draw do

  resources :projects do
    resources :lists
  end

  resources :todos

  devise_for :users

  root :to => 'projects#index'

end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :title, :todos

  belongs_to :project

  has_many :todos

end

app/models/project.rb
class Project < ActiveRecord::Base

  attr_accessible :name, :public
  belongs_to :user
  has_many :lists
  has_many :todos, :through => :lists

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  attr_accessible :name, :due_date, :list_id
  validates_presence_of :name

  belongs_to :list
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def new
    @list = List.new
  end

  def create
    @list = List.new(params[:list])
    @list.project_id = params[:project_id]
    @project = Project.find(@list.project.id)
    @todo = Todo.new
    respond_to do |format|
      if @list.save
        format.html { redirect_to project_path(@project) }
        format.js
      else
        format.html { render :action => "new" }
        format.js
      end
    end
  end

  def edit
  end

  def index
  end

  def destroy
  end

  def update
  end

  def show

  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @projects = Project.all
    @project = Project.new
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    @project.user_id = current_user.id
    if @project.save
      redirect_to project_path(@project)
    else
      render "new"
    end #end if
  end

  def show
    @project = Project.find(params[:id])
    @list = List.new
    @project = Project.find(params[:id])
    @todo = Todo.new
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(params[:todo])
    respond_to do |format|
      if @todo.save
        format.html { redirect_to project_path(@todo.list.project) }
        format.js
      else
        format.html { render :action => "new" }
        format.js
      end
    end
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

#   def can_view?
# #    current_user == project.user_id
# #return true
#   #else return false
#   end

end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Basecramp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<div class="navbar">
  <div class="navbar-inner">
      <div class="container">
<h1>Basecramp Projects</h1>
    </div>
  </div>
</div>


<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<p><div id="account">
  <% if current_user %>
    <span>Welcome, <%= current_user.email %></span>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path %>
  <% end %>
</div></p>

<body>

<%= yield %>

</body>
</html>

app/views/lists/_list.html.erb
<%= form_for([@project, @list], :remote => true) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p><strong>Add New List</strong></p>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/_todo_list_show.erb
<div id="list">
<h2>Lists</h2>
<!-- warn "@projects"
warn @projects.inspect -->
<% @project.lists.each do |list| %>
  <h3><%=link_to list.title, project_list_path(@project, list)%></h3><br>

  <%= render :partial => "todos/todo", :locals => {:list => list} %>
  <%= render :partial => "todos/add_todo", :locals => {:list => list} %>

  <% end %></div>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/create.js.erb
$('#list').html("<%= j(render :partial => "todo_list_show") %>");

app/views/lists/destroy.html.erb
<h1>Lists#destroy</h1>
<p>Find me in app/views/lists/destroy.html.erb</p>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>

app/views/lists/new.html.erb
<h1>Lists#new</h1>
<p>Find me in app/views/lists/new.html.erb</p>

app/views/lists/show.html.erb
<h1>Lists#show</h1>
<p>Find me in app/views/lists/show.html.erb</p>

app/views/lists/update.html.erb
<h1>Lists#update</h1>
<p>Find me in app/views/lists/update.html.erb</p>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.select :public, [['Public', true],['Private', false]] %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<table>
  <tr>
    <th>Projects</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<div>

</div>

<% @projects.each do |project| %>
  <tr>
    <td><%= link_to "#{project.name}", project_path(project) %></td>

  </tr>
<% end %>
</table>

<p>
  <%= button_to "Create Project", new_project_path, :method => :get %>
</p>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h1><%=@project.name%></h1>

 <%= render :partial => "lists/todo_list_show" %>
<br>

  <%= render :partial => "/lists/list" %>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>

app/views/todos/_add_todo.html.erb
<%= form_for(@todo, :remote => true) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :due_date %>
    <%= f.text_field :due_date %>
  </div>

  <div class="field">
    <%= f.hidden_field(:list_id, :value => list.id) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<div id="todo-<%= "#{list.id}" %>">
<h4>Todos</h4>

<table>
<% list.todos.each do |todo| %>
<tr>
  <td><%= todo.name %></td>
  <td><%= todo.due_date %></td>
</tr>
  <% end %>

</table>
<br>
</div>

app/views/todos/create.html.erb
<h1>Todos#create</h1>
<p>Find me in app/views/todos/create.html.erb</p>

app/views/todos/create.js.erb
$('#todo-<%= @todo.list.id %> table tbody').append("<tr><td><%= @todo.name %></td><td><%= @todo.due_date %></td></tr>");

app/views/todos/destroy.html.erb
<h1>Todos#destroy</h1>
<p>Find me in app/views/todos/destroy.html.erb</p>

app/views/todos/edit.html.erb
<h1>Todos#edit</h1>
<p>Find me in app/views/todos/edit.html.erb</p>

app/views/todos/index.html.erb
<h1>Todos#index</h1>
<p>Find me in app/views/todos/index.html.erb</p>

app/views/todos/new.html.erb
<h1>Todos#new</h1>
<p>Find me in app/views/todos/new.html.erb</p>

app/views/todos/show.html.erb
<h1>Todos#show</h1>
<p>Find me in app/views/todos/show.html.erb</p>

app/views/todos/update.html.erb
<h1>Todos#update</h1>
<p>Find me in app/views/todos/update.html.erb</p>